export { account } from './accountScreen'
export { favor } from './favoriteScreen'
export { home } from './homeScreen'
export { login } from './loginApp'
export { register } from './registerApp'
export { splash } from './splashScreen'
export { terms } from './termsConditions'
export { welcome } from './welcomeScreen'
